// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StuyvesantHighSchool.Data;

namespace StuyvesantHighSchool.Migrations
{
    [DbContext(typeof(StuyDbContext))]
    [Migration("20201017141903_ComplexDataModel")]
    partial class ComplexDataModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StuyvesantHighSchool.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("TeacherID");

                    b.HasKey("DepartmentID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Score");

                    b.Property<int>("StudentID");

                    b.Property<int>("SubjectID");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.RoomAssignment", b =>
                {
                    b.Property<int>("TeacherID");

                    b.Property<string>("Room")
                        .HasMaxLength(50);

                    b.HasKey("TeacherID");

                    b.ToTable("RoomAssignment");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EnrollmentDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID");

                    b.Property<int>("Credits");

                    b.Property<int>("DepartmentID");

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.HasKey("SubjectID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.SubjectAssignment", b =>
                {
                    b.Property<int>("SubjectID");

                    b.Property<int>("TeacherID");

                    b.HasKey("SubjectID", "TeacherID");

                    b.HasIndex("TeacherID");

                    b.ToTable("SubjectAssignment");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("JoinDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("TeacherID");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.Department", b =>
                {
                    b.HasOne("StuyvesantHighSchool.Models.Teacher", "Admin")
                        .WithMany()
                        .HasForeignKey("TeacherID");
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.Enrollment", b =>
                {
                    b.HasOne("StuyvesantHighSchool.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StuyvesantHighSchool.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.RoomAssignment", b =>
                {
                    b.HasOne("StuyvesantHighSchool.Models.Teacher", "Teacher")
                        .WithOne("RoomAssignment")
                        .HasForeignKey("StuyvesantHighSchool.Models.RoomAssignment", "TeacherID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.Subject", b =>
                {
                    b.HasOne("StuyvesantHighSchool.Models.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StuyvesantHighSchool.Models.SubjectAssignment", b =>
                {
                    b.HasOne("StuyvesantHighSchool.Models.Subject", "Subject")
                        .WithMany("SubjectAssignment")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StuyvesantHighSchool.Models.Teacher", "Teacher")
                        .WithMany("SubjectAssignments")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
